CREATE TABLE `FAQ`(
	`aswear` VARCHAR(40),
	`category` VARCHAR(40),
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`faqID` BIGINT NOT NULL,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`profileID` VARCHAR(40),
	`question` VARCHAR(40),
	`SoftDeleteFlag` BOOLEAN,
	`workflowStatus` VARCHAR(40),
	PRIMARY KEY(`faqID`)
);
ALTER TABLE `FAQ`
	ADD CONSTRAINT `2470d33d64fe38fa49f5f37f69c4b8` UNIQUE KEY(`faqID`);
