CREATE TABLE `Goals`(
	`cardioPoints` BIGINT,
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`goalsID` BIGINT NOT NULL,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`profileID` BIGINT,
	`SoftDeleteFlag` BOOLEAN,
	`steps` BIGINT,
	PRIMARY KEY(`goalsID`)
);
ALTER TABLE `Goals`
	ADD CONSTRAINT `42cdc1df33dc108e0aad3d1089641d` UNIQUE KEY(`goalsID`);
