CREATE TABLE `Glucose`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`date` DATETIME(3),
	`glucose` BIGINT,
	`glucoseID` BIGINT NOT NULL,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`profileID` BIGINT,
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`glucoseID`)
);
ALTER TABLE `Glucose`
	ADD CONSTRAINT `1c558fbfa4cd3c87449248fb58998d` UNIQUE KEY(`glucoseID`);
